flags: {}
extra-package-dbs: []
packages:
  - '.'
  - location:
      git: git@github.com:eryx67/api-builder.git
      commit: cd59e846d286d55358ccf2f7e6ccdb396020364d
extra-deps:
- attoparsec-binary-0.2
resolver: lts-5.6
